name: Continuous Integration with Github Actions

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Docker Hub Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    
    - name: Build Application JAR
      working-directory: ./HelpDesk/HelpDesk
      run: mvn clean package

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/helpdesk-backend:latest .
    
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/helpdesk-backend:latest

    - name: Tag Docker Image with Run ID
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/helpdesk-backend:latest ${{ secrets.DOCKER_USERNAME }}/helpdesk-backend:${{ github.run_id }} 
        docker push ${{ secrets.DOCKER_USERNAME }}/helpdesk-backend:${{ github.run_id }}
